name: Badges endpoint

on:
  push:
    branches:
    - badges
    
jobs:
  api_methods:
    name: API Methods
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout [badges] branch
      uses: actions/checkout@v2
        
    - name: Generate JSON
      working-directory: .github/badges/api_methods
      run: php -f badge.php
      
    - name: Commit changes
      # This action checks for changes before commit
      # You'll get an error 129 from git when pushing unchanged working tree
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Actions
        author_email: orkan@github-actions.com
        message: "Generate endpoint JSON for API Methods"
        add: ".github/badges/api_methods/badge.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Save artifact
      uses: actions/upload-artifact@v1
      with:
        name: api_methods.json
        path: .github/badges/api_methods/badge.json
